# Generated by Django 4.0.2 on 2022-11-14 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('file', models.FileField(null=True, upload_to='audios/')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 11, 14, 14, 33, 57, 976312, tzinfo=utc))),
            ],
        ),
    ]
