# Generated by Django 4.1.3 on 2022-11-15 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='message',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 57, 0, 48337, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 57, 0, 48846, tzinfo=datetime.timezone.utc))),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
        ),
    ]
