# Generated by Django 4.1.3 on 2022-11-15 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customer_message_alter_customer_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 58, 44, 684587, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 8, 58, 44, 684073, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Audios',
        ),
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
    ]
