# Generated by Django 4.1.3 on 2022-11-15 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_audio_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 9, 1, 52, 493381, tzinfo=datetime.timezone.utc)),
        ),
    ]
