# Generated by Django 4.1.3 on 2022-11-15 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customer_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 9, 2, 36, 103112, tzinfo=datetime.timezone.utc)),
        ),
    ]
