# Generated by Django 4.1.3 on 2022-11-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customer_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='file',
        ),
        migrations.AddField(
            model_name='audio',
            name='file',
            field=models.FileField(null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
