# Generated by Django 4.1.3 on 2022-11-15 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customer_file_audio_file_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 11, 27, 22, 194393, tzinfo=datetime.timezone.utc)),
        ),
    ]
