# Generated by Django 4.1.3 on 2022-11-15 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_audio_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='name',
        ),
        migrations.AlterField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 12, 32, 19, 178122, tzinfo=datetime.timezone.utc)),
        ),
    ]
