# Generated by Django 4.1.3 on 2022-11-15 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_audio_name_alter_audio_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 13, 28, 7, 835202, tzinfo=datetime.timezone.utc)),
        ),
    ]
