# Generated by Django 4.1.3 on 2022-11-16 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_audio_date_created_alter_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 9, 49, 13, 11602, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
