# Generated by Django 4.1.3 on 2022-11-16 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_audio_date_created_alter_audio_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='audio',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 10, 4, 37, 53504, tzinfo=datetime.timezone.utc)),
        ),
    ]
